/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.storemis.ui;

import com.example.storemis.dao.CustomerDAO;
import com.example.storemis.dao.OrdersDAO;
import com.example.storemis.dao.OrdersInfoDAO;
import com.example.storemis.dao.ProductsDAO;
import com.example.storemis.dao.impl.CustomerDAOImpl;
import com.example.storemis.dao.impl.OrdersDAOImpl;
import com.example.storemis.dao.impl.OrdersInfoDAOImpl;
import com.example.storemis.dao.impl.ProductsDAOImpl;
import com.example.storemis.entity.Customer;
import com.example.storemis.entity.Orders;
import com.example.storemis.entity.OrdersInfo;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class SalesUI extends javax.swing.JFrame {

    OrdersDAO ordersDAO = null;
    DefaultTableModel model = null;

    /**
     * Creates new form NewSales
     */
    public SalesUI() {
        initComponents();
        currentDate();
        billNo();
        FillComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_date = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_fName = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sales = new javax.swing.JTable();
        txt_grandTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btn_addSales = new javax.swing.JButton();
        txt_orderId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_lName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btn_home = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cmb_productName = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_availableQty = new javax.swing.JTextField();
        txt_salesQty = new javax.swing.JTextField();
        txt_unitPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        btn_addToCart = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_date.setEditable(false);

        jLabel1.setText("Date:");

        jLabel2.setText("First Name");

        jLabel3.setText("Phone No.");

        jLabel4.setText("Address");

        tbl_sales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity", "Unit Price", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_salesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_sales);

        txt_grandTotal.setText("0");

        jLabel11.setText("Grand Total:");

        btn_addSales.setText("Perform Sales");
        btn_addSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addSalesActionPerformed(evt);
            }
        });

        txt_orderId.setEditable(false);
        txt_orderId.setText("0");

        jLabel12.setText("Bill No.");

        jLabel13.setText("Last Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(24, 24, 24)
                                .addComponent(txt_orderId, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_fName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(txt_lName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt_phone)
                                        .addGap(8, 8, 8))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_date, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addComponent(txt_address))
                            .addComponent(jLabel4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txt_grandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(btn_addSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txt_orderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_grandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_addSales)
                .addGap(112, 112, 112))
        );

        btn_home.setText("Home");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        cmb_productName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Product..." }));
        cmb_productName.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_productNamePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel5.setText("Product Name:");

        jLabel6.setText("Available Qty:");

        jLabel7.setText("Unit Price:");

        jLabel8.setText("Sales Qty:");

        txt_availableQty.setEditable(false);
        txt_availableQty.setText("0");

        txt_salesQty.setText("0");

        txt_unitPrice.setEditable(false);
        txt_unitPrice.setText("0");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setText("Add to Cart:");

        jLabel10.setText("Total:");

        txt_total.setText("0");
        txt_total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_totalMouseClicked(evt);
            }
        });

        btn_addToCart.setText("Add To Cart");
        btn_addToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addToCartActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_productName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_availableQty)
                            .addComponent(txt_total)
                            .addComponent(btn_addToCart, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_salesQty)
                            .addComponent(txt_unitPrice))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_productName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txt_availableQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txt_unitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txt_salesQty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_addToCart)
                        .addGap(18, 18, 18)
                        .addComponent(btn_edit)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete))
                    .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_home))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_home)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void billNo() {
        try {
            ordersDAO = new OrdersDAOImpl();
            txt_orderId.setText(String.valueOf(ordersDAO.getLastId() + 1));
        } catch (ClassNotFoundException | SQLException ce) {

        }

    }

    public void currentDate() {
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        txt_date.setText(year + "/" + (month + 1) + "/" + day);
    }

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:

        clearAll();
    }//GEN-LAST:event_btn_clearActionPerformed

    public void clearAll() {

        txt_fName.setText("");
        txt_lName.setText("");
        txt_phone.setText("");
        txt_address.setText("");
        txt_grandTotal.setText("0");
        txt_availableQty.setText("0");
        txt_salesQty.setText("0");
        txt_unitPrice.setText("0");
        txt_total.setText("0");

        model = (DefaultTableModel) tbl_sales.getModel();
        model.setRowCount(0);

        billNo();

        btn_addSales.show(true);
    }

    public void FillComboBox() {
        ProductsDAO productDAO = new ProductsDAOImpl();
        try {
            productDAO.getAll().forEach(p -> {
                cmb_productName.addItem(p.getProductName());
            });
        } catch (ClassNotFoundException | SQLException ce) {

        }
    }

    private void cmb_productNamePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_productNamePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        ProductsDAO productDAO = new ProductsDAOImpl();
        String selected = (String) cmb_productName.getSelectedItem();
        try {
            productDAO.getByName(selected).forEach(p -> {
                txt_availableQty.setText(String.valueOf(p.getQuantity()));
                txt_unitPrice.setText(String.valueOf(p.getUnitPrice()));
            });
            txt_salesQty.setText("0");
            txt_total.setText("0");
        } catch (Exception e) {

        }

    }//GEN-LAST:event_cmb_productNamePopupMenuWillBecomeInvisible

    private void txt_totalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_totalMouseClicked
        // TODO add your handling code here:
        double unitPrice = Double.parseDouble(txt_unitPrice.getText());
        int salesQty = Integer.parseInt(txt_salesQty.getText());
        double mul = unitPrice * salesQty;
        txt_total.setText(String.valueOf(mul));
    }//GEN-LAST:event_txt_totalMouseClicked

    public void addRow() {
        model = (DefaultTableModel) tbl_sales.getModel();

        String productName = (String) cmb_productName.getSelectedItem();
        int qty = Integer.parseInt(txt_salesQty.getText());
        double unitPrice = Double.parseDouble(txt_unitPrice.getText());
        double total = Double.parseDouble(txt_total.getText());

        Object[] rowData = {productName, qty, unitPrice, total};
        model.addRow(rowData);

    }

    private void btn_addToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addToCartActionPerformed
        // TODO add your handling code here:
        addRow();
        grandTotal();

    }//GEN-LAST:event_btn_addToCartActionPerformed

    public void selectRow() {
        // get the model from the jtable
        model = (DefaultTableModel) tbl_sales.getModel();

        // get the selected row index
        int selectedRowIndex = tbl_sales.getSelectedRow();

        // set the selected row data into jtextfields
        cmb_productName.setSelectedItem(model.getValueAt(selectedRowIndex, 0).toString());
        txt_salesQty.setText(model.getValueAt(selectedRowIndex, 1).toString());
        txt_unitPrice.setText(model.getValueAt(selectedRowIndex, 2).toString());
        txt_total.setText(model.getValueAt(selectedRowIndex, 3).toString());
    }

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:        
        // get the model from the jtable
        model = (DefaultTableModel) tbl_sales.getModel();

        // get the selected row index
        int selectedRowIndex = tbl_sales.getSelectedRow();

        String productName = (String) cmb_productName.getSelectedItem();
        int qty = Integer.parseInt(txt_salesQty.getText());
        double unitPrice = Double.parseDouble(txt_unitPrice.getText());
        double total = Double.parseDouble(txt_total.getText());

        Object[] rowData = {productName, qty, unitPrice, total};

        model.setValueAt(rowData[0], selectedRowIndex, 0);
        model.setValueAt(rowData[1], selectedRowIndex, 1);
        model.setValueAt(rowData[2], selectedRowIndex, 2);
        model.setValueAt(rowData[3], selectedRowIndex, 3);

        grandTotal();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        model = (DefaultTableModel) tbl_sales.getModel();
        int row = tbl_sales.convertRowIndexToModel(tbl_sales.getSelectedRow());
        model.removeRow(row);

        grandTotal();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void tbl_salesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_salesMouseClicked
        // TODO add your handling code here:
        selectRow();
    }//GEN-LAST:event_tbl_salesMouseClicked

    private void btn_addSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addSalesActionPerformed
        // TODO add your handling code here:
        int customer_id = 0;
        String firstName = txt_fName.getText();
        String lastName = txt_lName.getText();
        String phone = txt_phone.getText();
        String address = txt_address.getText();
        int order_id = Integer.parseInt(txt_orderId.getText());

        if (firstName.length() == 0 || lastName.length() == 0) {
            JOptionPane.showMessageDialog(null, "Add first name and last name...");
        } else {
            try {
                //customer add or check
                CustomerDAO customerDAO = new CustomerDAOImpl();
                Customer customer = new Customer();

                customer.setFirstName(firstName);
                customer.setLastName(lastName);
                customer.setPhone(phone);;
                customer.setAddress(address);

                customer_id = customerDAO.getByName(firstName, lastName);
                //JOptionPane.showMessageDialog(null, customer_id);
                while (customer_id < 0) {
                    if (customerDAO.insert(customer) > 0) {
                        customer_id = customerDAO.getLastId();
                        //JOptionPane.showMessageDialog(null, customer_id);
                    }
                }

                //orders insert in database
                ordersDAO = new OrdersDAOImpl();
                Orders order = new Orders();

                order.setOrderId(order_id);
                order.setOrderCustomerId(customer_id);

                if (ordersDAO.insert(order) > 0) {
                    //JOptionPane.showMessageDialog(null, "Inserted in Orders");
                    model = (DefaultTableModel) tbl_sales.getModel();
                    OrdersInfoDAO ordersInfoDAO = new OrdersInfoDAOImpl();
                    OrdersInfo ordersInfo = new OrdersInfo();

                    //JOptionPane.showMessageDialog(null, model.getRowCount());
                    for (int i = 0; i < model.getRowCount(); i++) {
                        ProductsDAO productDAO = new ProductsDAOImpl();

                        int product_id = productDAO.getId(model.getValueAt(i, 0).toString());
                        int order_qty = Integer.parseInt(model.getValueAt(i, 1).toString());
                        double total = Double.parseDouble(model.getValueAt(i, 3).toString());

                        ordersInfo.setOrderId(order_id);
                        ordersInfo.setCustomerId(customer_id);
                        ordersInfo.setProductId(product_id);
                        ordersInfo.setOrderQty(order_qty);
                        ordersInfo.setTotal(total);

                        ordersInfoDAO.insert(ordersInfo);
                        //JOptionPane.showMessageDialog(null, "Inserted in OrdersInfo");

                        int qty = productDAO.getQty(product_id) - order_qty;
                        productDAO.deductQty(qty, product_id);
                        //JOptionPane.showMessageDialog(null, "Qty deducted");
                    }

                    JOptionPane.showMessageDialog(null, "Successful...");
                    btn_addSales.hide();

                } else {
                    JOptionPane.showMessageDialog(null, "Something went wrong...");

                }
            } catch (Exception e) {

            }
        }


    }//GEN-LAST:event_btn_addSalesActionPerformed

    public void grandTotal() {
        model = (DefaultTableModel) tbl_sales.getModel();
        double grandTotal = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            double total = Double.parseDouble(model.getValueAt(i, 3).toString());
            grandTotal += total;
        }
        txt_grandTotal.setText(Double.toString(grandTotal));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addSales;
    private javax.swing.JButton btn_addToCart;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_home;
    private javax.swing.JComboBox cmb_productName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_sales;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_availableQty;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_fName;
    private javax.swing.JTextField txt_grandTotal;
    private javax.swing.JTextField txt_lName;
    private javax.swing.JTextField txt_orderId;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_salesQty;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_unitPrice;
    // End of variables declaration//GEN-END:variables
}
